---
- name: Launch iodine server in EC2
  hosts: localhost
  gather_facts: False
  vars:
    keypair: "swordfish"
    instance_type: t2.micro
    image: "ami-26c43149"
    region: "eu-central-1"
    iodine_hostname: "rita.iskuri.org"
  tasks:
    - name: Launch instance
      ec2:
         key_name: "{{ keypair }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         region: "{{ region }}"
         vpc_subnet_id: subnet-01c1217a
         assign_public_ip: yes
      register: ec2

    - name: Add new instance to host group
      add_host: hostname={{ item.public_ip }} groupname=launched
      with_items: ec2.instances

    - name: Wait for SSH to come up
      wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
      with_items: ec2.instances

    - name: Update DDNS
      uri:
        url: "https://dyn.dns.he.net/nic/update?hostname={{iodine_hostname}}&password={{lookup('env','HE_PASSWORD'}}&myip={{ec2.instances[0].public_ip}}"
        method: GET
        return_content: yes
        validate_certs: no
        status_code: 200
        HEADER_Content-Type: "application/x-www-form-urlencoded"
      register: output
      delegate_to: 127.0.0.1

- name: Install and configure Iodine
  hosts: launched
  become: True
  gather_facts: True
  vars:
    iodine_password: "kissa"
    iodine_tunnel_space: "10.0.0.1"
    iodine_hostname: "hayworth.iskuri.org"
  roles:
    - iodine_server


